apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: ashusvc1
  name: ashusvc1 # name of service 
spec:
  ports:
  - name: 5544-80
    port: 5544 # service IP will be bounded with this 
    protocol: TCP
    targetPort: 80 # target app pod port number
  selector: # POD FINDer uisng label of POD 
    run: ashuwebpod1 # label of POD 
  type: NodePort # type fo service
status:
  loadBalancer: {}
